### ISSUE TITLE
Tutorial for WIS CF WORKER

### ISSUE THREAD

**Issue by soulripper13** [JayPearlman/WIS-CF-Worker#2]
Could please post a details tutorial how to get it to work? I've got no idea how tobuse CF Worker.

**Comment by JayPearlman** [comment]
Hello. The existing tutorials from Cloudflare would be your best resource. 

[Get started - CLI · Cloudflare Workers docs](https://developers.cloudflare.com/workers/get-started/guide/)

[First Worker · Cloudflare Learning Paths](https://developers.cloudflare.com/learning-paths/workers/get-started/first-worker/)

If you are having an issue with this repo's code, please post specific details. Thanks
